name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "app/**"
      - "config/**"
      - "requirements.txt"
      - "Dockerfile"
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint, Format & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install lint and test tools
        run: pip install ruff black pytest httpx

      - name: Install application dependencies
        run: pip install -r requirements.txt

      - name: Lint with ruff
        run: ruff check app/ config/

      - name: Check formatting with black
        run: black --check app/ config/

      - name: Run unit tests
        env:
          API_KEY: ci-test-key-do-not-use-in-prod
          APP_ENV: test
          DB_PATH: /tmp/test_audit.db
          UPLOAD_DIR: /tmp/uploads
          PROCESSED_DIR: /tmp/processed
          SIGNED_DIR: /tmp/signed
          KEYS_DIR: /tmp/keys
        run: pytest backend/tests/ -v --tb=short -q

  docker-build:
    name: Docker Build Verification
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: secure-doc-ai:ci-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify container runs as non-root
        run: |
          docker run --rm \
            -e API_KEY=ci-test-key \
            secure-doc-ai:ci-${{ github.sha }} id
          # Must output uid=1001(appuser)
